Node 2: initialized as client with uuid: 00000000-0000-0000-0000-000000000002
NEW OPERATION
Node 2: doing command: create f0
Node 2: locking file: f0
Node 2: sending create rpc to 0 for file: f0
Node 0: sending ACK 0 to 2
Node 0: got packet protocol: RIO_CREATE
Node 0: receiving packet from RIOLayer
Node 0: creating file: f0
Node 0: marking file f0 RW for node 2
Node 2: sending ACK 0 to 0
Node 2: got packet protocol: RIO_SUCCESS
Node 2: receiving packet from RIOLayer
Node 2: creating file: f0
NEW OPERATION
Node 2: doing command: delete f0
Node 2: deleting file: f0
NEW OPERATION
Node 1: doing command: create f0
Node 1: locking file: f0
Node 1: sending create rpc to 0 for file: f0
Node 0: sending ACK 0 to 1
Node 0: got packet protocol: RIO_CREATE
Node 0: receiving packet from RIOLayer
Node 1: sending ACK 0 to 0
Node 1: got packet protocol: RIO_ERROR
Node 1: receiving packet from RIOLayer
Node 1: Error: f0 RIO_ERROR 11 FileAlreadyExists [UnknownError]
NEW OPERATION
Node 2: doing command: create f1
Node 2: locking file: f1
Node 2: sending create rpc to 0 for file: f1
Node 0: sending ACK 1 to 2
Node 0: got packet protocol: RIO_CREATE
Node 0: receiving packet from RIOLayer
Node 0: creating file: f1
Node 0: marking file f1 RW for node 2
Node 2: sending ACK 1 to 0
Node 2: got packet protocol: RIO_SUCCESS
Node 2: receiving packet from RIOLayer
Node 2: creating file: f1
NEW OPERATION
Node 2: doing command: create f2
Node 2: locking file: f2
Node 2: sending create rpc to 0 for file: f2
Node 0: sending ACK 2 to 2
Node 0: got packet protocol: RIO_CREATE
Node 0: receiving packet from RIOLayer
Node 0: creating file: f2
Node 0: marking file f2 RW for node 2
Node 2: sending ACK 2 to 0
Node 2: got packet protocol: RIO_SUCCESS
Node 2: receiving packet from RIOLayer
Node 2: creating file: f2
NEW OPERATION
Node 2: doing command: get f1
Node 2: getting file: f1
Node 2: Got file, contents below:
Node 2: 
NEW OPERATION
Node 2: doing command: append f0 738 
Node 2: appending to file: f0, contents: 738 
Node 2: caught exception (see below) [UnknownError]
java.lang.reflect.InvocationTargetException
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
java.lang.reflect.Method.invoke(Unknown Source)
Client.onCommand(Client.java:548)
CacheCoherenceTester.onCommand(CacheCoherenceTester.java:58)
CacheCoherenceTester.doOp(CacheCoherenceTester.java:270)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
java.lang.reflect.Method.invoke(Unknown Source)
edu.washington.cs.cse490h.lib.Callback.invoke(Callback.java:62)
edu.washington.cs.cse490h.lib.Simulator.handleEvent(Simulator.java:667)
edu.washington.cs.cse490h.lib.Simulator.executeEvents(Simulator.java:622)
edu.washington.cs.cse490h.lib.Simulator.doTimestep(Simulator.java:226)
edu.washington.cs.cse490h.lib.Simulator.start(Simulator.java:162)
edu.washington.cs.cse490h.lib.MessageLayer.main(MessageLayer.java:304)
